version: "3.7"
services:
  postgres:
    image: postgres
    container_name: querychallenge
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=queries_challenge
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
